<?php

namespace app\admin\controller;

use Cassandra\Date;
use think\Controller;
use think\Db;
use think\Request;

//符合 restful 资源控制器
class Homestay extends Controller
{
    public $code;
    public $validate;

    public function __construct(Request $request = null)
    {
        parent::__construct($request);
        $this->code = config('code');
        $validate = validate('Homestay');
    }

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //checkToken();
    }

    /**
     * 显示资源列表
     *index.php/api/Homestay
     * index.php/api/Homestay?page=
     * index.php/api/Homestay?page=2
     * @return \think\Response
     */
    public function index()
    {
        //
        $data = $this->request->get();
        //分页
        if (isset($data['page'])&&!empty($data['page'])){
            $page = $data['page'];
        }else{
            $page = 1;
        }
        if (isset($data['limit'])&&!empty($data['limit'])){
            $limit = $data['limit'];
        }else{
            $limit = config('homestayLimit');
        }
        //处理搜索条件
        $where =[];
        if (isset($data['hcity'])&&!empty($data['hcity'])){
            $where['hcity'] =['like','%'.$data['hcity'].'%'];
        }
        if (isset($data['hname'])&&!empty($data['hname'])){
            $where['hname'] = ['like','%'.$data['hname'].'%'];
        }
        if (isset($data['cname'])&&!empty($data['cname'])){
            $where['cname'] = $data['cname'];
        }
//        $result = Db::table('homestay')->alias('h')->join(['category'=>'c'],'h.cid = c.cid','left')->field('hid,cname,hname,hprovince,hcity,haddress,')->where($where)->paginate($limit,false,['page'=>$page]);
        $result = Db::view('homestay','hid,hname,hdesc,hprovince,hcity,harea,haddress,hprice,hscore,hstatus,htag,htime')->view('category','cname','homestay.cid=category.cid')->where($where)->paginate($limit,false,['page'=>$page]);
        $homestay = $result->items();
        $total = $result->total();
        if($homestay&&$total){
            return json([
                'code'=>$this->code['success'],
                'msg'=>'数据查询成功',
                'total'=>$total,
                'data'=>$homestay
            ]);
        }else{
            return json([
                'code'=>$this->code['fail'],
                'msg'=>'数据添加失败'
            ]);
        }
    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        //
    }

    /**
     * 保存新建的资源
     *
     * @param \think\Request $request
     * @return \think\Response
     */
    public function save(Request $request)
    {
        $data = $this->request->post();
        //$this->validate->sence()->check();
        $hname = $data['hname'];
        $isExist = Db::table('homestay')->where('hname','=',$hname)->count();
        if($isExist){
            return json([
                'code'=>$this->code['fail'],
                'msg'=>'该民宿名已经存在'
            ]);
        }

        $data['htime'] =time();
        $result = Db::table('homestay')->insert($data);
        if($result){
            return json([
                'code'=>$this->code['success'],
                'msg'=>'数据添加成功',
            ]);
        }else{
            return json([
                'code'=>$this->code['fail'],
                'msg'=>'数据添加失败'
            ]);
        }
    }

    /**
     * 显示指定的资源
     *
     * @param int $id
     * @return \think\Response
     */
    public function read($id)
    {
        $data = Db::table('homestay')->where('hid','=',$id)->find();
        if($data){
            //处理轮播图字段
            $data['hbanner1']=explode(',',$data['hbanner']);
            return json([
                'code'=>$this->code['success'],
                'msg'=>'数据加载成功',
                'data'=>$data
            ]);
        }else{
            return json([
                'code'=>$this->code['fail'],
                'msg'=>'数据加载失败'
            ]);
        }

    }

    /**
     * 显示编辑资源表单页.
     *
     * @param int $id
     * @return \think\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * 保存更新的资源
     *
     * @param \think\Request $request
     * @param int $id
     * @return \think\Response
     */
    public function update(Request $request, $id)
    {
        //
        $data = $this->request->put();
//        return json([
//            'code'=>200,
//            'msg'=>$data
//        ]);

        $data = array_filter($data,function ($k){
           return $k !== 'hbanner1';
        },2);
       // var_dump($data);
        $hname = $data['hname'];
        $isExist = Db::table('homestay')->where('hname','=',$hname)->count();
        $result = Db::table('homestay')->where('hid','=',$id)->update($data);
        if($result){
            return  json([
                'code'=>$this->code['success'],
                'msg'=>'数据更新成功'
            ]);
        }else{
            return  json([
                'code'=>$this->code['fail'],
                'msg'=>'数据更新失败'
            ]);

        }
    }

    /**
     * 删除指定资源
     *
     * @param int $id
     * @return \think\Response
     */
    public function delete($id)
    {
        //
       $result = Db::table('homestay')->where('hid','=',$id)->delete();
       if($result){
           return json([
               'code'=>$this->code['success'],
               'msg'=>'删除信息成功'
           ]);
       }else{
           return json([
               'code'=>$this->code['fail'],
               'msg'=>'删除信息失败'
           ]);
       }
    }
}
